- name: Run Maestro tests
  uses: reactivecircus/android-emulator-runner@v2

  env:
    APP_NAME: chandigarh
    APK_URL: https://github.com/HiteshGit001/smook-test/releases/download/ci-build-1318/app-chandigarh-release.apk

    # APP_NAME: ${{ github.event.inputs.app }}
    # APK_URL: ${{ github.event.inputs.apk_url }}

  with:
    api-level: 30
    target: default
    arch: x86_64
    profile: pixel_5
    cores: 3
    ram-size: 4096M
    heap-size: 1024M
    disk-size: 6000M
    disable-animations: true
    force-avd-creation: true
    emulator-boot-timeout: 1200
    emulator-options: >
      -no-snapshot
      -no-window
      -gpu off
      -noaudio
      -no-boot-anim
      -camera-back none
      -camera-front none
      -wipe-data

    script: |
      adb start-server
      adb devices
      bash run_tests.sh
